### PR TITLE
Do not start Feature Flag polling if no API Key

### PR DESCRIPTION
**Pull request by mariusandra**
## Changes

- To complement https://github.com/PostHog/posthog/issues/2150#issuecomment-732174233 and https://github.com/PostHog/posthog/pull/2473
- Moves the "no personal api key found" warning and `return` statement one level higher, thus never starting the poller if no api key found.

### CODE REVIEW

**Comment by Twixes** [comment]
Hmm, why does this use a personal API key instead of a project key? @timgl

**Review by timgl — APPROVED** [review]

**Comment by timgl** [comment]
@Twixes b/c project keys don't have access to the feature flags (and we wouldn't want it too as that could be confidential experiments etc)

**Comment by mariusandra** [comment]
I merged it... but now I have no idea how to release a new version onto pip. @timgl can you help here? I see @paolodamico is also a maintainer on pip.

**Comment by paolodamico** [comment]
I can help with the release

**Pull request merged**
